# Workflow for processing and publishing bikeshed documents to github pages

name: publish documents
on:
  push:
    # only concerned with changes in the main branch
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: install bikeshed
        run: |
          python3 -m pip install --upgrade bikeshed
          bikeshed update

      - name: generate html
        run: |
          for bsdoc in *.bs; do bikeshed spec $bsdoc; done
          for bsdoc in primer/*.bs; do bikeshed spec $bsdoc; done

      - name: generate svg
        run: for diagram in primer/*.mmd; do docker run --rm -v "$PWD:/data" minlag/mermaid-cli -i /data/$diagram; done

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: .
          personal_token: ${{ secrets.GITHUB_TOKEN }}
