# Workflow for verifying bikeshed documents processing

name: verify processing
on:
  # only concerned with gating PRs to the main branch
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: install bikeshed
        run: |
          python3 -m pip install --upgrade bikeshed
          bikeshed update

      - name: generate html
        run: |
          for bsdoc in *.bs; do bikeshed spec $bsdoc; done
          for bsdoc in primer/*.bs; do bikeshed spec $bsdoc; done

      - name: generate svg
        run: for diagram in primer/*.mmd; do docker run --rm -v "$PWD:/data" minlag/mermaid-cli -i /data/$diagram; done

